language: elixir

elixir:
  - 1.4.2

otp_release:
  - 19.0

services:
  - postgresql

before_script:
  - psql -c "create user exmud with password 'exmud'; create database exmud_test;" -U postgres
  - mix ecto.migrate

script:
  - "mix do deps.get, test && mix compile && mix coveralls.travis"

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

env:
  - MIX_ENV=test