language: elixir

elixir:
  - 1.4.2

otp_release:
  - 19.0

services:
  - postgresql

before_script:
  - psql -c "CREATE USER exmud WITH PASSWORD 'exmud'" -U postgres
  - psql -c "CREATE DATABASE exmud_test" -U postgres
  - psql -c "ALTER DATABASE exmud_test OWNER TO exmud" -U postgres
  - mix ecto.migrate

script:
  - "mix do deps.get, test && mix compile && mix coveralls.travis"

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

env:
  - MIX_ENV=test