language: elixir

elixir:
  - 1.3.3
  
otp_release:
  - 19.0
  
services:
  - postgresql
  
before_script:
  - psql -c 'create database exmud_test_repo;' -U postgres
  - mix ecto.migrate
  
script: 
  - "mix do deps.get, test && mix compile && mix coveralls.travis"
  
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  
env:
  - MIX_ENV=test